services:
  - type: web
    name: myUniverse
    runtime: docker
    plan: free

    envVars:
      - key: APP_ENV
        value: prod

      - key: APP_SECRET
        sync: false

      - key: DATABASE_URL
        sync: false

    buildCommand: |
      composer install --no-dev --optimize-autoloader
    
    startCommand: |
      apache2-foreground
