controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

show_constellation:
    path: /constellation/{id}
    controller: App\Controller\ConstellationController::show
    methods: ['POST']